version: "3.5"
services:
  webserver:
    build: ./
    volumes:
    - ./nginx:/etc/nginx/templates
    - ./src/cgi:/cgi-bin:rw
    - ./src/templates:/templates:rw
    ports:
    - "80:80"
    environment:
      SHELL_ENV: ${SHELL_ENV:-development}

